version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/packages/bots/discord/1375476122061508619"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "AlessVett"
    assignees:
      - "AlessVett"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    groups:
      python-minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Future: GitHub Actions dependencies when workflows are added
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   labels:
  #     - "dependencies"
  #     - "github-actions"

  # Future: npm dependencies when frontend is added
  # - package-ecosystem: "npm"
  #   directory: "/packages/frontend"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
  #   labels:
  #     - "dependencies"
  #     - "javascript"
