version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: whiteout-discord-bot
    restart: unless-stopped
    environment:
      # Discord Configuration
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      
      # MongoDB Configuration
      MONGODB_URI: mongodb://mongodb:27017/whiteout_bot
      
      # API Configuration
      API_BASE_URL: ${API_BASE_URL}
      API_KEY: ${API_KEY}
      
      # Bot Configuration
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-en}
      EMBED_COLOR: ${EMBED_COLOR:-0x5865F2}
      
    depends_on:
      - mongodb
    networks:
      - bot-network
    volumes:
      # Persist logs if needed
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:7.0
    container_name: whiteout-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: whiteout_bot
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - bot-network
    ports:
      # Expose MongoDB only on localhost for security
      - "127.0.0.1:27017:27017"
    command: mongod --auth
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local