global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # API Gateway metrics
  - job_name: 'api-gateway'
    dns_sd_configs:
      - names:
          - 'tasks.api-gateway'
        type: 'A'
        port: 8000
    metrics_path: '/metrics'

  # Discord Bot metrics
  - job_name: 'discord-bot'
    dns_sd_configs:
      - names:
          - 'tasks.discord-bot'
        type: 'A'
        port: 8001
    metrics_path: '/metrics'

  # Consul metrics
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # Docker Swarm metrics
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: node
      - source_labels: [__meta_dockerswarm_node_platform_architecture]
        target_label: platform_architecture